name: Build

on: push

jobs:
  build-test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - name: Install GCC-ARM
        run: sudo apt-get install gcc-arm-none-eabi

      - name: Build
        run: make