name: Update root-repo

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          repository: club-rockets/anirniq
          submodules: true
          token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}

      - name: Update submodule
        working-directory: mission
        run: git checkout ${{ github.ref }}

      - name: Commit
        run: |
          git add mission
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'bot@noreply.github.com'
          git commit -m "[auto] Update Mission submodule"
          git push
